workflows:
  android-build:
    name: Build dengan Setup Lengkap
    scripts:
      - name: Install Gradle
        script: |
          export GRADLE_URL=https://services.gradle.org/distributions/gradle-8.0-bin.zip
          wget $GRADLE_URL -O gradle.zip
          unzip gradle.zip
          export PATH=$PATH:$(pwd)/gradle-8.0/bin
      - name: Build APK
        script: |
          gradle assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/*.apk
