workflows:
  android-build:
    name: Build Android
    environment:
      groups:
        - android
    scripts:
      - name: Setup Gradle
        script: |
          chmod +x ./gradlew
      - name: Build Debug
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
