workflows:
  build-game:
    name: Build Dasar
    scripts:
      - name: Build Debug
        script: |
          ./gradlew assembleDebug
      - name: Build Release 
        script: |
          ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/apk/**/*.apk
    publishing:
      email:
        recipients: ["email@anda.com"] # Ganti dengan email Anda
